name: Submit contracts hash to Subscan

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Compile contract and Submit hash to Subscan
        shell: bash
        env:
          working_directory: ./example
          manifest_path: Cargo.toml
          toolchain: stable
          compiler_tag: v2.2.1
          rust_version: 1.68.0
          compiler_args: --release
        run: |
          wget https://storage.googleapis.com/wasm-compile-artifacts.gcs.subscan.io/submit-contracts-hash/latest/submit-contracts-hash
          chmod +x submit-contracts-hash && ./submit-contracts-hash


